# Generated by Django 3.2.18 on 2023-02-20 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
