# Generated by Django 3.2.18 on 2023-02-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.IntegerField(blank=True, choices=[(1, 'Horror'), (2, 'Fantasy'), (3, 'Hard Sci-Fi'), (4, 'Space Opera'), (5, 'Comedy')]),
        ),
    ]
