# Generated by Django 3.2.18 on 2023-02-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0004_alter_subgenre_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_genre',
            field=models.IntegerField(blank=True, choices=[(1, 'Horror'), (2, 'Fantasy'), (3, 'Hard Sci-Fi'), (4, 'Space Opera'), (5, 'Comedy'), (6, 'Other')]),
        ),
        migrations.AlterField(
            model_name='subgenre',
            name='name',
            field=models.IntegerField(blank=True, choices=[(1, 'Horror'), (2, 'Fantasy'), (3, 'Hard Sci-Fi'), (4, 'Space Opera'), (5, 'Comedy'), (6, 'Other')]),
        ),
    ]
