# Generated by Django 3.2.18 on 2023-02-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0005_auto_20230224_1741'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubGenre',
        ),
    ]
