# Generated by Django 3.2.18 on 2023-02-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0006_delete_subgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3),
        ),
    ]
