# Generated by Django 3.2.18 on 2023-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0007_alter_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_genre',
            field=models.IntegerField(blank=True, choices=[(1, 'Horror'), (2, 'Fantasy'), (3, 'Hard Sci-Fi'), (4, 'Space Opera'), (5, 'Comedy'), (7, 'Cyberpunk'), (8, 'Apocalyptic'), (9, 'Other')]),
        ),
    ]
