# Generated by Django 3.2.18 on 2023-03-10 12:17

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0009_alter_book_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('residence', models.CharField(max_length=60)),
                ('bio', models.TextField()),
                ('famous_books', models.CharField(max_length=200)),
                ('author_image', cloudinary.models.CloudinaryField(default='default_image', max_length=255, verbose_name='image')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
