# Generated by Django 3.2.18 on 2023-03-12 17:00

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0011_auto_20230310_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
