# Generated by Django 3.2.18 on 2023-03-12 17:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sfblog', '0012_alter_author_author_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='author_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
