# Generated by Django 3.2.18 on 2023-03-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0015_userprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='sub_genre',
            field=models.IntegerField(blank=True, choices=[(0, 'Not sure'), (1, 'Horror'), (2, 'Fantasy'), (3, 'Hard Sci-Fi'), (4, 'Space Opera'), (5, 'Comedy'), (7, 'Cyberpunk'), (8, 'Apocalyptic'), (9, 'Other')], default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
