# Generated by Django 3.2.18 on 2023-03-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sfblog', '0016_auto_20230319_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
